# Variables: ["shared-var-group", "qa-var-group"]

trigger:
  - qa

resources:
  repositories:
  - repository: templates
    type: git
    name: templates

jobs:
- template: pipelines/func-app.node.azure-pipelines.yml@templates
